### ISSUE TITLE
implicit await promises

### ISSUE THREAD

**Issue by smeijer** [arthurfiorette/proposal-safe-assignment-operator#14]
I'm wondering, assume a function that returns a promise, like:

```js
async function read(filename) { 
  throw new Error(`file '${filename}' can't be read`); 
}
```

Not awaiting it when using `?=` would not make sense, as it wouldn't catch anything.

```js
const [error, data] ?= read('some-file');
```

The solution is to use `await read`, but I wonder if it makes sense to have an implicit await when a function returns a promise. People can still use `const promise = read('some file)` if they don't intend to `await` it. And then call `[error, data] ?= await promise` later.

**Comment by arthurfiorette** [comment]
Im not sure if making things implicit is the way to go...

Also, how this would play up with a function like this:

```ts
function example() {
  if(condition) {
    throw new Error('sync')
  }

  return new Promise((res, rej) => {
    return reject(new Error('async'))
  })
}
```

In which the function could either throw directly or return a promise that might throw as well.
