### ISSUE TITLE
Error propagation

### ISSUE THREAD

**Issue by nikolalukovic** [arthurfiorette/proposal-safe-assignment-operator#16]
I think the syntax for error propagation should be a part of this proposal. It would be nice to be able to leave the error handling to the caller (unless top level ofc) and just grab the result if it's successful.

Regular call:
```js
const [error, result] = try someMethod();
```
With error propagation:
```js
const result = try? someMethod();
```

**Comment by arthurfiorette** [comment]
You are overthinking...

---

Error propagation:

```ts
const result = someMethod();
```

**Comment by nikolalukovic** [comment]
Sure. The syntax is the least important thing about it right now as long as it's clearly defined how it's going to work. Though I'd much rather it be explicit with `try?`.

**Comment by arthurfiorette** [comment]
> backend in TypeScript needs a typed errors.

That's not what this proposal is trying to acheive neither wants to do so.

**Comment by DScheglov** [comment]
@arthurfiorette 

yes, exactly, and that is a main problem with the proposal.

TypeScripts also needs the `Symbol.result` and it needs `try?` and `try!`, but these symbol and operators has a different meaning.

I've written a little bit more here: https://github.com/microsoft/TypeScript/issues/56365#issuecomment-2295322047
