### ISSUE TITLE
How can I contribute this is a really cool idea

### ISSUE THREAD

**Issue by dolev146** [arthurfiorette/proposal-safe-assignment-operator#19]
How can I contribute this is a really cool idea

**Comment by arthurfiorette** [comment]
share your ideas and suggestions on open issues

**Comment by dolev146** [comment]
I want to be part of the development , to push code

**Comment by ljharb** [comment]
it's a spec, there isn't any code that matters until it's time to implement (stage 2.7, which is a lonnnnnng way from no stage at all)

**Comment by dolev146** [comment]
So can u keep me updated I want to code

**Comment by arthurfiorette** [comment]
lol

**Comment by anacierdem** [comment]
I know this is not TC39 but I just want to remind there will be a code of conduct if this ever gets to stage 0.

https://tc39.es/code-of-conduct/
