### ISSUE TITLE
Dont use two identifiers, just catch thrown errors

### ISSUE THREAD

**Issue by KevsRepos** [arthurfiorette/proposal-safe-assignment-operator#26]
I appreciate the effort to turn javascript into a language that can handle errors as values. I just think we have several issues with the current proposal and so here is mine.

1. I think the `?=` operator is ambigious. It means totally different things in other languages and it is not semantic. Newcomers can not guess what it does by looking at it.
2. The idea that the error can as well be ignored is not ideal in my opinion.

So My proposal looks like this:
```js
catch const foo = bar();

if(foo instanceof Error) {

} else {

}
```
This method should work out of box with every assignment of any type. We do not need to change the definition of already existing functions or objects, meaning we can gradually refactor already existing code.
Furthermore, it is to mention that this syntax is very readable and understandable, even for non javascript developers.
You are also naturally forced to handle the error and Typescript can easily point out that `foo` may be a thrown value.
And if the `catch` keyword is omitted, higher level catch blocks will simply catch the thrown error.

### What if values are thrown that are not an instance of `Error`?
In that case you should simply be aware that your value can be of an unexpected type, which you have to handle as well. One way is to inverse the condition:
```ts
function bar(): Baz {
  return new Baz();
}

catch const foo = bar();

if(!foo instanceof Baz) {
  //Must have thrown, handle error
} else {

}
```
Even if the `Baz` didnt throw, it still returned something the consumer assumingly did not expect, so has to be handled anyway.

Thank you very much for allowing me to contribute my idea.

**Comment by arthurfiorette** [comment]
This don't work. The problem is that js can `throw { a : 1 }` and this would return false when checking for `error instanceof Error`.

**Comment by KevsRepos** [comment]
> This don't work. The problem is that js can `throw { a : 1 }` and this would return false when checking for `error instanceof Error`.

I already gave a solution to this. If you know what the return value should be, then you can check the type of the returned value. Another way to solve this issue is to add a possibility to check if the value was thrown by either adding a way to check if a value was thrown, or by putting a catch block after the expression.
```
catch const foo = bar();

if(wasThrown()) {

}
```

```js
const foo = bar() catch(e) {

}
```

**Comment by arthurfiorette** [comment]
Assigning them to a single variable is not the solution and shouldn't be. There's no prior language that decided to reuse the same variable for ok/err and they have a valid reason for that.

**Comment by KevsRepos** [comment]
> There's no prior language that decided to reuse the same variable for ok/err and they have a valid reason for that.

Rust does exactly this with the `Result` enum which can be represented by `Ok` or `Err`. Functions defined to return the `Result` enum return only one value and the consumer has to check the type of the value.
Especially Rusts error handling is one of the most used arguments for rust, as it is unambiguous, so I really want to protest against a premature rejection of a system that is proven to be working very well.
