### ISSUE TITLE
The tuple leads to a unsound type, it also breaks the already existing allSettled pattern

### ISSUE THREAD

**Issue by gabrielricardourbina** [arthurfiorette/proposal-safe-assignment-operator#27]
Using a tuple as a result of this operator is a mistake.

JS allows promises to be rejected with any type, it also allows promises to be resolved with any type

The tuple cannot guarantee that is possible to know if the given promise failed or passed

For example
```javascript
const [result, error] ?= await Promise.reject(undefined)
```
```javascript
const [result, error] ?= await Promise.resolve(undefined)
```

Without knowing the implementation there is no guaranteed way of knowing if the promise failed or passed, 

This has already been solved by [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)

This new syntax **must** be syntactic sugar for this helper function

```javascript
async function settled(promise) {
  const [settled] = await Promise.allSettled([promise])
  return settled
}
```
## Addendum
As per https://github.com/arthurfiorette/proposal-safe-assignment-operator/issues/27#issuecomment-2301983200, the structure of the resulting object might need to be different from the PromiseSettledResult for synchronous functions, although I don't mind using the same type

**Comment by gabrielricardourbina** [comment]
See https://github.com/arthurfiorette/proposal-safe-assignment-operator/issues/3#issuecomment-2292678889

**Comment by arthurfiorette** [comment]
The allSettled pattern is just for promises, `status: 'fulfilled',` and `status: 'rejected'` is as well.

**Comment by gabrielricardourbina** [comment]
@arthurfiorette You're right, I'm overlooking sync functions, in any case it has to be a discriminable object.

Personally I don't mind using the same type as Promise.allSettled for sync functions

**Comment by arthurfiorette** [comment]
It also doesn't have to be an object, falsy throwns are catched by the implementation too, i just didn't added it to the written spec yet because i wanted to see other solutions.

https://github.com/arthurfiorette/tuple-it/blob/32dc86108ae76e5c118bedf320c574c6ac8d6e41/index.js#L13

**Comment by gabrielricardourbina** [comment]
Just to clarify

How's the tuple result when a falsy value is thrown? it gets converted to something else?
