### ISSUE TITLE
The assignment operator should not have the responsibility of flow control

### ISSUE THREAD

**Issue by rafageist** [arthurfiorette/proposal-safe-assignment-operator#37]
## The problem

**Question: Does the proposed operator control flow?  
Answer: Yes!**

Exceptions are meant for handling unexpected situations that a function cannot control, such as missing dependencies, network errors, .... **An assignment operator should not be responsible for controlling the flow of exceptions**—that’s what structures like `try-catch` are designed for. Mixing assignment with flow control can blur the lines between different responsibilities in the code, leading to confusing and error-prone practices.

In the proposal, when you write ...

```js
const [err, foo] ?= bar()
```

... and an exception occurs in `bar()` (or in any dependency of `bar()`), **the operator is capturing that exception**, acting like a hidden `try-catch`. This means the operator is controlling the flow of the program, which is not the purpose of an assignment operator. This can lead to unclear code and bad practices by making exceptions less explicit and harder to manage.

By embedding exception handling directly into an assignment operator, the proposal risks confusing the role of assignment versus flow control, potentially leading to less readable and maintainable code.

If the problem raised is with flow control in `try-catch`, then the proposal should be to improve flow control using new control structures, not assignment operators. 

## Detailed comparison

Here's how the steps compare between a traditional `try-catch` block and the proposed `?=` operator:

### Traditional `try-catch` Block

1. **Start capturing exceptions:** The `try` block begins, which prepares the program to catch any exceptions that may be thrown within its scope.
2. **Execute code:** The program executes the code inside the `try` block.
3. **Stop capturing exceptions:** The `try` block ends, and control is handed to the `catch` block if an exception occurs.
4. **Exception handling:**
    - **Yes:** If an exception occurs, it is passed to the `catch` block, where it can be handled explicitly.
    - **No:** If no exception occurs, the program skips the `catch` block and continues with the next line after the `try-catch`.
5. **Continue program flow:** The program continues executing normally after the `try-catch`.

### Proposed `?=` Operator

1. **Prepare memory zone:** Allocate memory to store either the result or an error.
2. **Operator starts capturing exceptions:** The `?=` operator prepares to intercept any exceptions that may occur during the execution of the function.
3. **Execute code:** The function is executed.
4. **Operator stops capturing exceptions:** The operator ends its interception.
5. **Exception handling:**
    - **Yes:** If an exception occurs, the operator stores the exception in the prepared memory zone.
    - **No:** If no exception occurs, the operator stores the function's result in the memory zone.
6. **Continue program flow:** The program continues executing after the operation, with the memory zone now containing either the result or the exception.

### Key Differences

- **Explicit vs. Implicit Control:** In the traditional method, control flow is explicit and visible in the code. The `try-catch` block clearly shows where exceptions are handled. In the proposed method, the control flow is implicit within the operator, which could make it harder to understand at a glance how exceptions are being handled.

- **Flexibility:** The traditional `try-catch` allows for more complex and fine-grained control over how different types of exceptions are handled. **Breaking the rule of language**, the proposed operator simplifies error handling but at the cost of flexibility and clarity.

- **Code Readability:** The traditional method maintains clear separation between normal code execution and error handling. The proposed operator blurs this line, potentially making the code less readable and maintainable.

## What can you do?

You can imagine many ECMA-compliant variants and you might end up concluding that the current `try-catch` is the best one.

```js
// 1. inline solution

try let result = await fetch(...) catch err
try result = await fetch(...) catch err
try result = await fetch(...)
let result = await fetch(..) catch err

// ...

// 2. catch like switch-case
try:
// ...
catch err:
 // ...
finally:  // (or finally; / break; to finish...)
// ...

// 3. catch for any ECMA blocks (anonymous,, functions, cases, classes, if, ...)

{   ....   } catch (err) {   } finally {   ...   }

function foo() {  } catch (err) {  } finally {   ...   }

if (...) {   } catch {   } finally {   ...   }

class Person { ..... } catch (err) { ... } finally {   ...   } // if something happens inside the class
```

**Comment by arthurfiorette** [comment]
Every operator control flows in a way or another.
`??=` controls flow.
`||=` controls flow.
Even a simple `=` controls flow.
They are assignment operators and depending on what they assigned the code flow WILL change.

**Comment by ljharb** [comment]
@arthurfiorette not to condone the behavior here, but i fwiw don't see any compelling argument for assignment having to do with anything, and an inline expression-based solution seems like the only viable approach to me personally.

**Comment by rafageist** [comment]
@arthurfiorette 

There seems to be a misunderstanding of my intent. I have taken the time to help you based on my three decades of experience in this field. It is true that I do not gain anything from it. It is about responsibility.

```js
/* Saving a value in RAM is not the same as telling the processor which is the next instruction to execute. */
```

I am not proposing inline solutions as a panacea. For me at this point the language is fine and my proposal essay is not necessary and has nothing to do with your proposal.

I was illustrating that the current `try-catch` is necessary and sufficient, that the other ideas lead to more complex problems that are difficult to deal with, and how the current language can be used to handle exceptions explicitly and clearly.

My main argument is that introducing an operator that handles exceptions implicitly in the context of an assignment is not advisable because it mixes responsibilities in a confusing way.

As for the statement that "every assignment changes the flow of the program," I agree that any operation can affect the flow (after the assignment), but there **_is a big difference between a change in the state of variables and explicit control of the program flow_** in an **imperative programming**: 

In my opinion, in the opinion of an expert committee, and in the rules that guide the development of programming languages, assignment operators should not be responsible for exception handling, as this blurs the clear separation of responsibilities that is critical in designing maintainable code.

I welcome the discussion and the opportunity to share different perspectives, but I think it is important to remain clear on the purpose of each language construct.
