### ISSUE TITLE
what about `throw;` (and `throw undefined || null || 0 || false || "";`)

### ISSUE THREAD

**Issue by Arlen22** [arthurfiorette/proposal-safe-assignment-operator#46]
What if a function throws undefined? I thought I should mention it. I can't really think of any way to gracefully handle that. I mean, a void function that throws is now just returning, but maybe that's the point, since if you're throwing undefined anyway, is anyone really going to care?

I'm willing to bet that a function which throws undefined really doesn't care any more. 

I think the same logic probably applies to throwing the other falsey values.

I thought of rethrowing anything that doesn't extend Error, but I don't think we should rethrow anything. If someone isn't throwing an Error instance, they're not expecting anyone else to use their code.

**Comment by Arlen22** [comment]
Would there be benefit in providing a Boolean third argument which indicates success?

**Comment by Arlen22** [comment]
this is more or less addressed in #30

**Comment by arthurfiorette** [comment]
https://github.com/arthurfiorette/proposal-safe-assignment-operator/issues/30#issuecomment-2351688712
