### ISSUE TITLE
Why error first?

### ISSUE THREAD

**Issue by yishayhaz** [arthurfiorette/proposal-safe-assignment-operator#49]
> TLDR;
`const [data, error]` will be more suitable for the use cases this feature is designed for than `const [error, data]`

This feature could be very useful in scenarios where multiple try-catch blocks are required, such as hashing a password and saving it to a database. In most cases, however, it will likely be used for simpler tasks, such as parsing a string into JSON or handling other straightforward operations where error handling isn't necessarily required, and a simple `null` return is sufficient.

As the feature is intended for these simpler use cases, many developers will likely use const [_, data] ?= func();, which naturally ignores the error. To improve code readability and maintain consistency in error handling, returning the error as the second value (const [data, error] ?= func();) would be a more intuitive approach.

### Examples

```typescript
function readData(str: string): Data | null {
    const [_, data] ?= JSON.parse(str);
    return data;
}
```

```typescript
async function hashPassword(password: str): string | null {
    const [_, hashedPassword] ?= crypto.hash(password);
    return hashedPassword;
}
```

### My suggestion

```typescript
function readData(str: string): Data | null {
    const [data] ?= JSON.parse(str);
    return data;
}
```

```typescript
async function hashPassword(password: str): string | null {
    const [hashedPassword] ?= crypto.hash(password);
    return hashedPassword;
}
```

**Comment by DScheglov** [comment]
@yishayhaz 

The proposal tends to use `try` expression instead of the `?=`. But it is a small off-topic.

The following fragment:

```typescript
function readData(str: string): Data | null {
    const [_, data = null] = try JSON.parse(str);
    return data;
}
```

ignores error, but does it a less implicitly then the next does:

```typescript
function readData(str: string): Data | null {
    const [data = null] = try JSON.parse(str);
    return data;
}
```

The implicit error ignoring -- actually is an issue, that makes code
less relialbe.

**Comment by arthurfiorette** [comment]
If the developer wants to ignore the error, then he will do it no matter what we end up.

However 

```ts
const [_, data] = try exp()
```

is much more explicit than

```ts
const [data] = try exp()
```

**Comment by DScheglov** [comment]
Actually, "error-first" is a pattern nodejs was launched with, so to return error first is something like respecting old tradition.

**Comment by DScheglov** [comment]
@yishayhaz 

There is a big difference between:
 - "ignoring error" and 
 - "ignoring error implicitly"

So, the problem not in the ignoring. The problem is in impliciticy.

> I also think that for more complex use cases using a try-catch block will still be the preferred way, so this feature is basically designed for the more simpler use cases where we tend to not care about the error.

Actually, the aim of `try`-expression (or `safe-assignment`-operator) is to make complex things simpler. So, whenever we can use `try ... catch` we must be able to use `try`-expression.

**Comment by yishayhaz** [comment]
For cases with a lot of crashing points that you only care about a binary "success" or "failed" result, it will be more convenient to use `try-catch` block

And, is there an actual benefit to the error-first approach? because my argument is that it's less convenient and less readable code, and even if you disagree-there's no actual downside for data-first approach.

**Comment by yishayhaz** [comment]
Actually after a short research I found that most languages do it differently, it's something like `var x = try func();` and `x` will be `null` if an error was thrown.
This leaves room for the original try-catch block but solves the use cases where you just need to safely do something without handling the potential error, wdyt?

## Examples

### Swift
https://swiftplayground.run/

```swift
let number = try? Int("123")

print("The converted value is: \(number)")
```

### Kotlin
https://play.kotlinlang.org/
```kotlin
fun main() {
    val inputString = "1a23"

    val number = try { inputString.toInt() } catch (e: NumberFormatException) { null }

    println("The converted value is: $number")
}
```

### Rust
https://play.rust-lang.org
```rust
fn parse_number(s: &str) -> Option<i32> {
    s.parse::<i32>().ok()
}

fn process_number(s: &str) -> Option<i32> {
    let number = parse_number(s)?; // none or number
    Some(number)
}

fn main() {
    let input = "42";
    
    match process_number(input) {
        Some(result) => println!("{}", result),
        None => println!("None"),
    }
}
```

**Comment by DScheglov** [comment]
@yishayhaz 

You pointed the different cases here:

- **Swift**: `try?` - is a way to explcitly convert possible error to the `nil`
- **Cotlin**: it is an explicit error handling, having the separated control flow for the error case
- **Rust**: it is not about errors at all. And actually it is about `?` operator, that is missing in this proposal at all.

If you want to refer to other languages, it is much more relevant to mention the Go, where the functions return
`(data, error)` tuple, and actually the idea of this proposal is inspired exactly by Go-s error handling.

```go
f, err := os.Open("filename.ext")
if err != nil {
    log.Fatal(err)
}
// do something with the open *File f
```
([Source](https://go.dev/blog/error-handling-and-go))

Despite of that, the error-first approach is more explicit, then data-first one.

**Comment by yishayhaz** [comment]
My point was that error handling isn’t necessary in many scenarios, and adopting a model similar to those languages would leave room for using try-catch blocks.

And honestly, I don't think I can present a stronger argument than your Go example, and I’ve already shared examples from other languages and arguments for developer experience. Since you’re still committed to the error-first approach, I’ll go ahead and close this issue.

Best of luck with this feature, will be cool either way

**Comment by DScheglov** [comment]
@yishayhaz 

> My point was that error handling isn’t necessary in many scenarios.

Actually all what you mentioned in this issue is exactly about error handling. 
To use the default value when the computation fails -- is a kind of error handling.

By the way, now we are discussing `[ok, error, value]` approach )
