### ISSUE TITLE
How can I use it in my nextJs project

### ISSUE THREAD

**Issue by pasternak-karmel** [arthurfiorette/proposal-safe-assignment-operator#51]
I'm writting the new syntaxe but not working, How can i solve it. Thanks

**Comment by DScheglov** [comment]
@pasternak-karmel 
it is just a proposal, it is not ready to use.
Currently there is no even babel plugin for that.

You can try to use some libraries for you project:
Like [safely-try](https://www.npmjs.com/package/safely-try)
or [do-try-tuple](https://www.npmjs.com/package/do-try-tuple)

**Comment by pasternak-karmel** [comment]
ohh got it. thanks for your help
