### ISSUE TITLE
Syntax overkill in basic example

### ISSUE THREAD

**Issue by Akiyamka** [arthurfiorette/proposal-safe-assignment-operator#7]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

not related

### A minimal reproducible example

https://stackoverflow.com/help/minimal-reproducible-example.

### Description

not related

### Steps to Reproduce

not related

### Expected Behavior

instead of

```js
const [error, result] ?= example()

function example() {
  [Symbol.result]() {
    return [
      new Error("Error"),
      null
    ]
  },
}
```
you can write just
```js
const exampleBox = (...args) => example(...args) ?? [new Error("Error"), null]
const [error, result]  = exampleBox()
```

**Comment by arthurfiorette** [comment]
Yes the syntax is overkill for this super simple surrealistic example. I put it there to showcase how it works in objects, later meant to be used as class/object properties in which you don't know when and where the function is going to be called.
