### ISSUE TITLE
Poll requires X account

### ISSUE THREAD

**Issue by jbkly** [arthurfiorette/proposal-safe-assignment-operator#8]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Versions

https://x.com/arthurfiorette/status/1823901476260844023

### A minimal reproducible example

https://x.com/arthurfiorette/status/1823901476260844023

### Description

The [poll to decide which syntax to use](https://x.com/arthurfiorette/status/1823901476260844023) requires an "X" account  to view or contribute. 

Please consider providing a way to participate for those who do not have an X account.

### Steps to Reproduce

1. Ensure you do not have an X account (if you do have an account, delete it).
2. Navigate to [poll to decide which syntax to use](https://x.com/arthurfiorette/status/1823901476260844023)

### Expected Behavior

I expect to be able to view and participate in the poll to decide which syntax to use, even though I have deleted my X account.

**Comment by arthurfiorette** [comment]
you're right! changing it now to

https://smartpolls.co.uk/p/77575

**Comment by jbkly** [comment]
Thanks!

**Comment by jbkly** [comment]
The examples are nice on the X version though
